import {db} from './db';
import {randomInt,randomBytes,createCipheriv,createDecipheriv,createHash} from 'node:crypto';
export type EventRow={id:number;name:string;prefix:string;ssid:string;quantity:number;expires_at:Date;session_seconds:number;simultaneous:number;down_mbps:number;up_mbps:number;created_at:Date};
export async function ensureVoucherTables(){await db.query(`CREATE TABLE IF NOT EXISTS c3_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(180) NOT NULL,prefix VARCHAR(60) NOT NULL,ssid VARCHAR(120) NOT NULL DEFAULT '',quantity INT NOT NULL,expires_at DATETIME NOT NULL,session_seconds INT NOT NULL,simultaneous INT NOT NULL,down_mbps INT NOT NULL,up_mbps INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);await db.query(`CREATE TABLE IF NOT EXISTS c3_vouchers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id BIGINT UNSIGNED NOT NULL,username VARCHAR(128) NOT NULL UNIQUE,secret_enc TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(event_id),FOREIGN KEY(event_id) REFERENCES c3_events(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)}
const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
export function generatePassword(length=7){let out='';for(let i=0;i<length;i++)out+=alphabet[randomInt(alphabet.length)];return out}
function key(){const secret=process.env.VOUCHER_ENCRYPTION_KEY||process.env.SESSION_SECRET;if(!secret||secret.length<24)throw new Error('Configure VOUCHER_ENCRYPTION_KEY (32 bytes aleatórios em hex) ou SESSION_SECRET forte.');return createHash('sha256').update(secret).digest()}
export function encrypt(value:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv),data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64')}
export function decrypt(value:string){const b=Buffer.from(value,'base64'),dec=createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));dec.setAuthTag(b.subarray(12,28));return Buffer.concat([dec.update(b.subarray(28)),dec.final()]).toString('utf8')}
export function radiusDate(d:Date){const m=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return `${String(d.getUTCDate()).padStart(2,'0')} ${m[d.getUTCMonth()]} ${d.getUTCFullYear()} ${String(d.getUTCHours()).padStart(2,'0')}:${String(d.getUTCMinutes()).padStart(2,'0')}:${String(d.getUTCSeconds()).padStart(2,'0')}`}
